// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type User struct {
	ID               string     `db:"id" json:"id"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at"`
	Username         string     `db:"username" json:"username"`
	Email            string     `db:"email" json:"email"`
	EmailConfirmedAt *time.Time `db:"email_confirmed_at" json:"email_confirmed_at"`
	EmailConfirmCode *string    `db:"email_confirm_code" json:"email_confirm_code"`
	Password         string     `db:"password" json:"-"`
}
