// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"
)

const confirmEmail = `-- name: ConfirmEmail :exec
UPDATE user
SET 
    email_confirmed_at = CURRENT_TIMESTAMP,
    email_confirm_code = NULL
WHERE id = ? AND email_confirm_code = ?
`

type ConfirmEmailParams struct {
	ID               string  `db:"id" json:"id"`
	EmailConfirmCode *string `db:"email_confirm_code" json:"-"`
}

// ConfirmEmail
//
//	UPDATE user
//	SET
//	    email_confirmed_at = CURRENT_TIMESTAMP,
//	    email_confirm_code = NULL
//	WHERE id = ? AND email_confirm_code = ?
func (q *Queries) ConfirmEmail(ctx context.Context, arg ConfirmEmailParams) error {
	_, err := q.db.ExecContext(ctx, confirmEmail, arg.ID, arg.EmailConfirmCode)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user (
    id,
    username,
    email,
    email_confirm_code,
    password
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, created_at, username, email, email_confirmed_at, email_confirm_code, password
`

type CreateUserParams struct {
	ID               string  `db:"id" json:"id"`
	Username         string  `db:"username" json:"username"`
	Email            string  `db:"email" json:"email"`
	EmailConfirmCode *string `db:"email_confirm_code" json:"-"`
	Password         string  `db:"password" json:"-"`
}

// CreateUser
//
//	INSERT INTO user (
//	    id,
//	    username,
//	    email,
//	    email_confirm_code,
//	    password
//	) VALUES (
//	    ?, ?, ?, ?, ?
//	)
//	RETURNING id, created_at, username, email, email_confirmed_at, email_confirm_code, password
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.EmailConfirmCode,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.EmailConfirmedAt,
		&i.EmailConfirmCode,
		&i.Password,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user WHERE id = ?
`

// DeleteUser
//
//	DELETE FROM user WHERE id = ?
func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user WHERE email = ? LIMIT 1
`

// GetUserByEmail
//
//	SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user WHERE email = ? LIMIT 1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.EmailConfirmedAt,
		&i.EmailConfirmCode,
		&i.Password,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user WHERE id = ? LIMIT 1
`

// GetUserByID
//
//	SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user WHERE id = ? LIMIT 1
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.EmailConfirmedAt,
		&i.EmailConfirmCode,
		&i.Password,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user WHERE username = ? LIMIT 1
`

// GetUserByUsername
//
//	SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user WHERE username = ? LIMIT 1
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.EmailConfirmedAt,
		&i.EmailConfirmCode,
		&i.Password,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user ORDER BY created_at DESC
`

// ListUsers
//
//	SELECT id, created_at, username, email, email_confirmed_at, email_confirm_code, password FROM user ORDER BY created_at DESC
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.EmailConfirmedAt,
			&i.EmailConfirmCode,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user
SET 
    username = COALESCE(?1, username),
    email = COALESCE(?2, email),
    password = COALESCE(?3, password),
    email_confirmed_at = COALESCE(?4, email_confirmed_at),
    email_confirm_code = ?5
WHERE id = ?6
`

type UpdateUserParams struct {
	Username         *string    `db:"username" json:"username"`
	Email            *string    `db:"email" json:"email"`
	Password         *string    `db:"password" json:"-"`
	EmailConfirmedAt *time.Time `db:"email_confirmed_at" json:"email_confirmed_at"`
	EmailConfirmCode *string    `db:"email_confirm_code" json:"-"`
	ID               string     `db:"id" json:"id"`
}

// UpdateUser
//
//	UPDATE user
//	SET
//	    username = COALESCE(?1, username),
//	    email = COALESCE(?2, email),
//	    password = COALESCE(?3, password),
//	    email_confirmed_at = COALESCE(?4, email_confirmed_at),
//	    email_confirm_code = ?5
//	WHERE id = ?6
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.EmailConfirmedAt,
		arg.EmailConfirmCode,
		arg.ID,
	)
	return err
}
